(noise)noise = audiorecorder;
recordblocking(noise, 2);
recObj = audiorecorder;
disp('Start speaking.');
recordblocking(recObj, 2);
disp('End of Recording.');
myRecording = getaudiodata(recObj);
noisedata= getaudiodata;
filtered=myRecording-noisedata;
subplot(3,1,1);
plot(myRecording);
ylim([-0.5 0.5]);
title('noisy speech');
subplot(3,1,2);
plot(noisedata);
ylim([-0.5 0.5]);
title(sprintf('noise'));
subplot(3,1,3);
plot(filtered);
ylim([-0.5 0.5]);
title('filtered speech');